version: '3.9'

services: 
  db:
    image: mysql:latest
    container_name: LAN_Database
    command: --default-authentication-plugin=mysql_native_password
    volumes: 
      - ./Databases/data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'root'
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3308:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: LAN_PhpMyAdmin
    links:
      - db
    environment:
      PMA_HOST: db
    restart: always
    ports:
      - 8080:80
      
  LAN-Backend:
    container_name: LAN-Backend
    image: ${Docker_REGISRTY-} lanbackend
    build:
      context: Backend/LANBackend
      dockerfile: Dockerfile
      
    environment:
      - ASPNETCORE_URLS=http://+:5001
    
    ports:
      - "5002:5001"